"""
Run this once to seed your MongoDB with movie data:
    cd backend
    python seed.py
"""
from pymongo import MongoClient

client = MongoClient('mongodb://localhost:27017')
db     = client['movietime']

db['movies'].drop()
print("Seeding movies...")

MOVIES = [
    {
        'title':    'Good Bad Ugly',
        'image':    '/images/GBU',
        'bg_image': '/images/black.jpg',
        'duration': '2h 40m',
        'language': 'Tamil',
        'type':     '2D',
        'rating':   'U',
        'imdb':     8.2,
        'votes':    '124K',
        'price':    200,
        'genre':    'Action',
        'year':     2025,
        'tag':      'Advance Booking',
        'director': 'Adhik Ravichandran',
        'cast':     ['Ajith Kumar', 'Trisha', 'Prabhu Deva'],
        'desc':     'A high-octane action thriller featuring Ajith Kumar in a never-before-seen avatar. When a ruthless hitman is pulled back into the underworld, he must make impossible choices between loyalty and survival.',
        'shows': [
            {'id': 'gbu-pvr-1030', 'theatre': 'PVR IMAX – Madurai',  'time': '10:30 AM', 'seats_total': 80, 'price': 200},
            {'id': 'gbu-pvr-0230', 'theatre': 'PVR IMAX – Madurai',  'time': '02:30 PM', 'seats_total': 80, 'price': 200},
            {'id': 'gbu-pvr-0700', 'theatre': 'PVR IMAX – Madurai',  'time': '07:00 PM', 'seats_total': 80, 'price': 200},
            {'id': 'gbu-spi-1100', 'theatre': 'SPI Sathyam',          'time': '11:00 AM', 'seats_total': 80, 'price': 180},
            {'id': 'gbu-spi-0600', 'theatre': 'SPI Sathyam',          'time': '06:00 PM', 'seats_total': 80, 'price': 180},
            {'id': 'gbu-ags-0330', 'theatre': 'AGS Cinemas',           'time': '03:30 PM', 'seats_total': 80, 'price': 160},
        ],
    },
    {
        'title':    'SitaRam',
        'image':    '/images/sitaram.jpg',
        'bg_image': '/images/sitaram.jpg',
        'duration': '2h 15m',
        'language': 'Tamil',
        'type':     '2D',
        'rating':   'A',
        'imdb':     7.8,
        'votes':    '89K',
        'price':    180,
        'genre':    'Romance',
        'year':     2025,
        'tag':      '',
        'director': 'Hanu Raghavapudi',
        'cast':     ['Dulquer Salmaan', 'Mrunal Thakur', 'Sumanth'],
        'desc':     'A beautiful epic romance set in wartime India, depicting the timeless love between Sita and Ram across different eras. A visually stunning journey that redefines love, sacrifice and devotion through the ages.',
        'shows': [
            {'id': 'sr-pvr-1100', 'theatre': 'PVR IMAX – Madurai', 'time': '11:00 AM', 'seats_total': 80, 'price': 180},
            {'id': 'sr-pvr-0400', 'theatre': 'PVR IMAX – Madurai', 'time': '04:00 PM', 'seats_total': 80, 'price': 180},
            {'id': 'sr-spi-0900', 'theatre': 'SPI Sathyam',         'time': '09:00 AM', 'seats_total': 80, 'price': 160},
            {'id': 'sr-ags-0730', 'theatre': 'AGS Cinemas',          'time': '07:30 PM', 'seats_total': 80, 'price': 150},
        ],
    },
    {
        'title':    'Tharunam',
        'image':    '/images/tharunam',
        'bg_image': '/images/theatre.jpg',
        'duration': '1h 47m',
        'language': 'Tamil',
        'type':     '2D',
        'rating':   'U',
        'imdb':     7.2,
        'votes':    '42K',
        'price':    150,
        'genre':    'Drama',
        'year':     2025,
        'tag':      '',
        'director': 'M. Saravanan',
        'cast':     ['Arjun Das', 'Athulya Ravi', 'Aishwarya Rajesh'],
        'desc':     'An inspiring story about youth empowerment and self-discovery. A group of young rebels challenges the system to reclaim what was taken from them.',
        'shows': [
            {'id': 'tr-pvr-1200', 'theatre': 'PVR IMAX – Madurai', 'time': '12:00 PM', 'seats_total': 80, 'price': 150},
            {'id': 'tr-spi-0300', 'theatre': 'SPI Sathyam',         'time': '03:00 PM', 'seats_total': 80, 'price': 140},
            {'id': 'tr-ags-0630', 'theatre': 'AGS Cinemas',          'time': '06:30 PM', 'seats_total': 80, 'price': 130},
        ],
    },
    {
        'title':    'Maharaja',
        'image':    '/images/maharaja-2024.jpg',
        'bg_image': '/images/maharaja-2024.jpg',
        'duration': '2h 15m',
        'language': 'Tamil',
        'type':     '2D',
        'rating':   'A',
        'imdb':     8.6,
        'votes':    '198K',
        'price':    220,
        'genre':    'Thriller',
        'year':     2025,
        'tag':      'Hit',
        'director': 'Nithilan Swaminathan',
        'cast':     ['Vijay Sethupathi', 'Anurag Kashyap', 'Mamitha Baiju'],
        'desc':     'A gripping revenge thriller where a single father goes to extreme lengths to protect his family\'s honour. Filled with unexpected twists — Vijay Sethupathi at his career best.',
        'shows': [
            {'id': 'mh-pvr-0300', 'theatre': 'PVR IMAX – Madurai', 'time': '03:00 PM', 'seats_total': 80, 'price': 220},
            {'id': 'mh-spi-0600', 'theatre': 'SPI Sathyam',         'time': '06:00 PM', 'seats_total': 80, 'price': 200},
            {'id': 'mh-ags-0900', 'theatre': 'AGS Cinemas',          'time': '09:00 AM', 'seats_total': 80, 'price': 180},
        ],
    },
    {
        'title':    'Amaran',
        'image':    '/images/amaran.jpeg',
        'bg_image': '/images/amaran.jpeg',
        'duration': '2h 52m',
        'language': 'Telugu',
        'type':     '2D',
        'rating':   'U',
        'imdb':     8.9,
        'votes':    '302K',
        'price':    240,
        'genre':    'War / Drama',
        'year':     2025,
        'tag':      'Blockbuster',
        'director': 'Rajkumar Periasamy',
        'cast':     ['Sivakarthikeyan', 'Sai Pallavi', 'Bhuvan Arora'],
        'desc':     'Based on the true story of Major Mukund Varadarajan. A powerful tribute to the real heroes who sacrifice everything for the nation they love.',
        'shows': [
            {'id': 'am-pvr-0900', 'theatre': 'PVR IMAX – Madurai', 'time': '09:00 AM', 'seats_total': 80, 'price': 240},
            {'id': 'am-pvr-0130', 'theatre': 'PVR IMAX – Madurai', 'time': '01:30 PM', 'seats_total': 80, 'price': 240},
            {'id': 'am-pvr-0600', 'theatre': 'PVR IMAX – Madurai', 'time': '06:00 PM', 'seats_total': 80, 'price': 240},
            {'id': 'am-spi-1000', 'theatre': 'SPI Sathyam',         'time': '10:00 AM', 'seats_total': 80, 'price': 220},
        ],
    },
    {
        'title':    'LEO',
        'image':    '/images/leo.jpeg',
        'bg_image': '/images/leo.jpeg',
        'duration': '2h 30m',
        'language': 'Hindi',
        'type':     '2D',
        'rating':   'A',
        'imdb':     7.5,
        'votes':    '256K',
        'price':    260,
        'genre':    'Action',
        'year':     2025,
        'tag':      '',
        'director': 'Lokesh Kanagaraj',
        'cast':     ['Vijay', 'Trisha', 'Sanjay Dutt'],
        'desc':     'A mass action thriller starring Thalapathy Vijay as a seemingly gentle man forced to reveal his dark past when his family is threatened by the underworld.',
        'shows': [
            {'id': 'leo-pvr-0930', 'theatre': 'PVR IMAX – Madurai', 'time': '09:30 AM', 'seats_total': 80, 'price': 260},
            {'id': 'leo-pvr-0100', 'theatre': 'PVR IMAX – Madurai', 'time': '01:00 PM', 'seats_total': 80, 'price': 260},
            {'id': 'leo-spi-0500', 'theatre': 'SPI Sathyam',         'time': '05:00 PM', 'seats_total': 80, 'price': 240},
            {'id': 'leo-spi-0900', 'theatre': 'SPI Sathyam',         'time': '09:00 PM', 'seats_total': 80, 'price': 240},
            {'id': 'leo-ags-0730', 'theatre': 'AGS Cinemas',          'time': '07:30 PM', 'seats_total': 80, 'price': 220},
        ],
    },
    {
        'title':    'Dragon',
        'image':    '/images/dragon.jpg',
        'bg_image': '/images/dragon.jpg',
        'duration': '1h 47m',
        'language': 'English',
        'type':     '2D',
        'rating':   'U',
        'imdb':     7.0,
        'votes':    '38K',
        'price':    200,
        'genre':    'Fantasy',
        'year':     2025,
        'tag':      '',
        'director': 'Ashwath Marimuthu',
        'cast':     ['Pradeep Ranganathan', 'Anupama Parameswaran', 'Kayadu Lohar'],
        'desc':     'An epic fantasy adventure featuring a young warrior who bonds with a legendary dragon to defend his homeland from an ancient evil.',
        'shows': [
            {'id': 'dr-pvr-1130', 'theatre': 'PVR IMAX – Madurai', 'time': '11:30 AM', 'seats_total': 80, 'price': 200},
            {'id': 'dr-spi-0200', 'theatre': 'SPI Sathyam',         'time': '02:00 PM', 'seats_total': 80, 'price': 180},
            {'id': 'dr-ags-0530', 'theatre': 'AGS Cinemas',          'time': '05:30 PM', 'seats_total': 80, 'price': 160},
        ],
    },
]

db['movies'].insert_many(MOVIES)
print(f"✅ Inserted {len(MOVIES)} movies into MongoDB!")
print("You can now start the Django server: python manage.py runserver")
